# Generated by Django 3.0.1 on 2020-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200224_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='baja',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
