# Generated by Django 3.0.1 on 2020-03-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20200328_2029'),
        ('pedidos', '0003_auto_20200224_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='articulos',
        ),
        migrations.CreateModel(
            name='PedidoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='articulos.Articulo')),
            ],
            options={
                'verbose_name': 'Pedido-Articulo',
                'verbose_name_plural': 'Pedidos-Articulos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_articulo',
            field=models.ManyToManyField(related_name='articulos_pedidos', to='pedidos.PedidoArticulo'),
        ),
    ]
