# Generated by Django 3.0.1 on 2020-04-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
        ('clientes', '0004_auto_20200224_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=300, null=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquileres.Alquiler')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
