# Generated by Django 3.0.1 on 2020-04-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabanias', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='alquiler',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cabania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabanias.Cabania'),
            preserve_default=False,
        ),
    ]
