# Generated by Django 3.0.2 on 2020-06-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20200607_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='monto_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
