# Generated by Django 3.0.7 on 2020-06-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20200607_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
