# Generated by Django 3.0.1 on 2020-04-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'DISPONIBLE'), ('OCUPADO', 'OCUPADO'), ('RESERVADO', 'RESERVADO')], default='DISPONIBLE', max_length=300, null=True),
        ),
    ]
