# Generated by Django 3.0.1 on 2020-04-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_alquiler_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='articulo',
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
