# Generated by Django 3.0.1 on 2020-03-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='baja',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
