# Generated by Django 3.0.2 on 2020-02-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubros', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_created=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=900, null=True)),
                ('descripcion', models.CharField(max_length=800)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('alicuota_iva', models.DecimalField(blank=True, decimal_places=2, default=21, max_digits=12, null=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo_marca', to='marcas.Marca')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo_rubro', to='rubros.Rubro')),
            ],
            options={
                'verbose_name': 'Artículos',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
