# Generated by Django 3.0.2 on 2020-05-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectores', '__first__'),
        ('marcas', '__first__'),
        ('rubros', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=900, null=True)),
                ('descripcion', models.CharField(max_length=800)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('alicuota_iva', models.DecimalField(blank=True, decimal_places=2, default=21, max_digits=12, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('para_venta', models.BooleanField(blank=True, default=True, null=True)),
                ('baja', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo_marca', to='marcas.Marca')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo_rubro', to='rubros.Rubro')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sectores.Sector')),
            ],
            options={
                'verbose_name': 'Artículos',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
