# Generated by Django 3.0.2 on 2020-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articulo_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_compra',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
