# Generated by Django 3.0.1 on 2020-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20200224_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='para_venta',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='referencia',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
