# Generated by Django 3.0.1 on 2020-02-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='baja',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
