# Generated by Django 3.0 on 2020-01-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=600, null=True)),
            ],
            bases=('personas.persona',),
        ),
    ]
