# Generated by Django 3.0.2 on 2020-05-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('numero_documento', models.CharField(blank=True, max_length=300, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes')),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=300, null=True)),
                ('motivo', models.CharField(blank=True, max_length=600, null=True)),
                ('observacion', models.TextField(blank=True, max_length=300, null=True)),
                ('baja', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
            bases=('personas.persona',),
        ),
    ]
