# Generated by Django 3.0.2 on 2020-08-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='confirmacion_correo',
            field=models.BooleanField(default=False),
        ),
    ]
