# Generated by Django 3.0.1 on 2020-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200224_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
