# Generated by Django 3.0.2 on 2020-06-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de comprobantes',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
