# Generated by Django 3.0.2 on 2020-05-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_articulo', to='articulos.Articulo')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Cabania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('habitacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('DISPONIBLE', 'DISPONIBLE'), ('OCUPADO', 'OCUPADO'), ('RESERVADO', 'RESERVADO')], default='DISPONIBLE', max_length=300, null=True)),
                ('inventario', models.ManyToManyField(blank=True, to='cabanias.Inventario')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
            },
        ),
    ]
