# Generated by Django 3.0.2 on 2020-07-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabania',
            name='foto_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='cabanias'),
        ),
        migrations.AddField(
            model_name='cabania',
            name='foto_exterior',
            field=models.ImageField(blank=True, null=True, upload_to='cabanias'),
        ),
        migrations.AddField(
            model_name='cabania',
            name='foto_interior',
            field=models.ImageField(blank=True, null=True, upload_to='cabanias'),
        ),
    ]
